### ISSUE TITLE
What's the new feature IV means?

### ISSUE THREAD

**Issue by alawing** [j-e-k/pgoapi#11]
I put 0~100 or 0~1 for the percent?
and if the range of a pokemon's IV is 30%~80%, my IV value is 50%, will it be deleted?
also how you compares two pokemon's IV? like one is 80%~90%, and one is 20%~95%?

**Comment by j-e-k** [comment]
0~100 is the range 
The IV feature is experimental, it is calculated using the following logic:
https://www.reddit.com/r/TheSilphRoad/comments/4t7r4d/exact_pokemon_cp_formula/
I am not really clear on the specifics, I just added it in because it was requested. Hopefully someone else that actually plays PokemonGo can provide better documentation than I can.
