### ISSUE TITLE
Release All Pidgeotto/All automatic evolve pokemon 

### ISSUE THREAD

**Issue by panjitianda** [j-e-k/pgoapi#112]
Sometimes my bag full with Pidgeotto or raticate, or kakuna..
can i can set that release all Pidgeotto or evolved pokemon

**Comment by joychugh** [comment]
Add the evolved ones in the list to throw away, increase your CP requirement in config that should solve it. you can get the exact names of pokemon to add from the readme (there is section which gives you link to AEONLucid's repo with the names)

**Comment by Raynor1212** [comment]
Hey how do I populate the throw away? 

```
"THROW_POKEMON_NAMES": ["PIDGEY"],
```

I don't quite understand what kind of syntax the code want from me 

```
self.throw_pokemon_ids = map(lambda x: getattr(Enums_pb2, x), config.get("THROW_POKEMON_NAMES", []))
```

I tried to put them inside {} at some point 

```
"THROW_POKEMON_NAMES": {
	  "PIDGEY",
	  "Tangela",
	  "Drowzee",
	  "Fearow",
	  "Venonat",
	  "Pidgeot",
	  "Paras",
	  "Rhyhorn",
	  "Goldbat",
	  "Mankey",
	  "Krabby",
	  "Goldeen",
	  "Zubat",
	  "Spearow",
	  "Weedle",
	  "Rattata",
	  "Pinsir"},
      "MAX_CATCH_ATTEMPTS": 10
    },
```
but it's not the right thing to do

**Comment by joychugh** [comment]
readme has the link to the enum URL to get the exact names.

**Comment by Jay1** [comment]
@Raynor1212 nice try tho,

1. [The list](https://github.com/AeonLucid/POGOProtos/blob/master/src/POGOProtos/Enums/PokemonId.proto) @joychugh is talking about
2. it's **Gol**bat not **Gold**bat  so this one wouldn't have worked.
3. but your "main" mistake, the one that is preventing the work running at all is that you're using { } those brackets instead of [ ] square brackets.

**Comment by Raynor1212** [comment]
Thanks a lot guys!
