### ISSUE TITLE
Not catching anything?

### ISSUE THREAD

**Issue by sadatnfs** [j-e-k/pgoapi#536]
Ever since the last update, I haven't been catching anything (always failing). The bot seems to be walking around all good with my API key and such. Anyone else having this issue as well?

Edit: I finally caught a bird so never mind. Weird how having needy item farming turned on still catches pokemon. Thanks guys

**Comment by jekirl** [comment]
You could be banned, try logging in from the app itself

**Comment by sadatnfs** [comment]
Everything is working perfectly now! Just cleaned some things up in the JSON file.

**Comment by IllidanU** [comment]
@sadatnfs Sorry for replying to a closed issue.

But what did you cleaned?  Since I may have the same issue as you had.
- I can spin and get item. Receiving XP at the same time.
- I can successfully catch the lured Pokemon at the lure pokestop. Receiving XP at the same time.

But, I can't find any pokemon near by though the pokemon is actually everywhere.

**Comment by sadatnfs** [comment]
So I recloned and re-downloaded all the packages and then I realized that the new example json file had a lot of the fields inside the ptc account and I'm using a Google account. So I moved up all the stuff like needy farming etc under the Google account.

That being said, I'm pretty sure I got perma banned today, since my game keeps failing to find the server and haven't been able to access for the last 8 hours :(

**Comment by IllidanU** [comment]
OMG. I'm really sorry to hear that. Then I should wait for a while I think.

**Comment by sadatnfs** [comment]
Yeah Niantic's got a nasty ban wave on right now so might as well be safe :)
